### ISSUE TITLE
HTTP authentication not working?

### ISSUE THREAD

**Issue by PegasusPrime** [influxdata/influxdb-relay#13]
With http authentication enabled in influxdb, I cannot write to to the relay (port 8096 in this example).

Ex. authentication enabled writing to the relay
```
curl -i -XPOST -u test:test 'http://statsdb01:8096/write?db=mydb' --data-binary 'cpu_load_short,host=server01,region=us-west value=0.64'
HTTP/1.1 401 Unauthorized
Content-Type: application/json
Date: Fri, 22 Apr 2016 13:20:38 GMT
Content-Length: 50

{"error":"unable to parse Basic Auth credentials"}
```
Ex. Writing directly to influxdb (port 8086)
```
curl -i -XPOST -u test:test 'http://statsdb01:8086/write?db=mydb' --data-binary 'cpu_load_short,host=server01,region=us-west value=0.64'   
HTTP/1.1 204 No Content
Request-Id: ae607db4-088e-11e6-8012-000000000000
X-Influxdb-Version: 0.12.2
Date: Fri, 22 Apr 2016 13:32:38 GMT
```
Ex. authentication disabled writing to the relay
```
curl -i -XPOST 'http://statsdb01:8096/write?db=mydb' --data-binary 'cpu_load_short,host=server01,region=us-west value=0.64'                
HTTP/1.1 204 No Content
Date: Fri, 22 Apr 2016 13:35:50 GMT
```
Relay config:
```
[[http]]
name = "statsdb01"
bind-addr = "0.0.0.0:8096"
output = [
    { name="statsdb01", location = "http://statsdb01:8086/write", buffer-size = 1000, max-delay-interval = "1m" },
    { name="statsdb02", location = "http://statsdb02:8086/write", buffer-size = 1000, max-delay-interval = "1m" },
]
```

**Comment by cnelissen** [comment]
+1

Influxdb-relay needs to implement HTTP authentication and also needs to allow credentials to be specified per backend server i.e.

```
[[http]]
name = "statsdb01"
bind-addr = "0.0.0.0:8096"
auth-enabled = true // Same syntax as influxdb config
output = [
    { name="statsdb01", location = "http://statsdb01:8086/write", buffer-size = 1000, max-delay-interval = "1m", username="someuser", password="**password**"},
    { name="statsdb02", location = "http://statsdb02:8086/write", buffer-size = 1000, max-delay-interval = "1m", username="anotheruser", password="**password**" },
]
```

Without this authentication for influxdb is essentially unavailable if using influxdb-relay.

**Comment by gunnaraasen** [comment]
@cnelissen What's the use case for setting different credentials credentials per backend server?

**Comment by cnelissen** [comment]
I could think of a few reasons... 

1. Different departments maintain their own InfluxDB servers but want to share the same inflow from sensors etc.
2. Production and development servers have different credentials but want to share the same inflow from sensors etc.
3. Security conscious network admins want to limit the potential impact of a security breach and therefore create different logins for each server
4. Credentials are auto-generated for each server by a provisioning system, puppet/chef/etc.

There might be other use cases. In any case I think it is bad design to limit people by requiring every endpoint to share credentials.

Perhaps there could be a global backend username/password which could be overridden (if necessary) on a per-backend basis.

**Comment by joelegasse** [comment]
My concern about this proposal is that it is starting to talk about using the relay for unintended purposes. The primary goal of the relay is to create an HA setup, having different credentials per-backend and talking about different environments sharing a data stream seems like an accidental use-case for the relay.

Pass-through credentials might make sense, but in an HA setup, that just adds one more thing that needs to be synchronized across the backends or else we're risking data. It also will add race conditions and confusion on the client-side: If one backend server returns a `401`, then that  will get returned immediately, and the client will think the data write has failed, even though another server might return a `204` response. Regardless of which server replies  first, you will end up in a scenario where one server has data, and the other doesn't.

I think adding authentication into the mix will just make the relay less "friendly" to work with. We already have the issue of databases needing to be created on all backends before data should be written. Setting credentials in a config file will mean that the relay has to be restarted when a password changes, potentially losing any buffered data on that relay. Also, `4xx` responses are not retried, even if buffering is enabled.

I would rather keep the relay simple in purpose, and move the authentication concerns to a different level (TLS client certs at the load balancer, etc). Also, I would rather not promote using the relay for writing to disparate influxdb instances with no intention of HA.

**Comment by cnelissen** [comment]
Just to add another perspective, I could definitely agree that the primary use case should be HA, with anything else being an unsupported use case, in which case having different credentials per server would be unnecessary. I still think that authentication should clearly be a responsibility of the relay for a few reasons:

1. Not everyone will be using a load balancer to offload authentication concerns to (think simple HA such as round robin DNS, etc).
2. By not providing authentication support you would not allow different credentials per database, since auth has to be off currently. If you have network access to the relay you can write to every database - this is a problem.
3. It would also effectively disallow using the javascript InfluxDB library in an HA environment since clients would connect from different hosts/networks so network based ACL is impossible and most likely would not be considered a "trusted" device nor be managed by the same people/company running the server and therefore would not have a cert.

The auth passthrough should work great for most use cases without adding too many additional layers of complexity. The race condition you described would exist regardless of authentication, so it is a bit of a red herring in regards to this conversation.

**Comment by weshmashian** [comment]
Might be a good idea to explain my organization's use case, setup and reasoning behind the (cleaned up) auth passthrough pull in #19, but @cnelissen pretty much nailed it in previous response. I'll admit that I got carried away in the first iteration of the patch and that only passthrough idea should be presented and used.

We're handling metrics for ~3000 servers, split up in 40-50 clusters, each having anywhere between 2 and 100 servers. Each cluster has it's own dedicated write-only user and Influx database on a central InfluxDB cluster, load balanced by HAproxy.

All in all, setup is pretty much identical to the diagram presented in the documentation with writes going to relays (which dispatch those down the line) and all other queries hitting random Influx server directly.

The issue of databases having to be created beforehand and possibility of losing some data points on one of the Influx servers is a calculated risk we're taking and accounting for. We have relay buffers high enough so writes will survive regular server maintenance, and even if they don't, we can pull affected servers from HAproxy, keep writes going, and restore daily shards once they rotate.

So, in our scenario, if relay is not passing Authorized header the whole setup is pretty much useless as it would require turning off Influx authentication, which is simply not an option.

Hope this helps.

**Comment by rubycut** [comment]
Well, the http auth passing could potentially be disabled through config option. That would allow people to run relay in which ever purpose they want.

**Comment by joelegasse** [comment]
I've commented on #21, and I think that it's a good starting point for authentication being included in the relay. It will forward the `Authorization` header if it is present on an incoming request.

@cnelissen You're right, even with pass-through auth, we can still have different backends replying with 4xx/2xx and possibly create a confusing scenario to the client. Should this just be considered a "quirk" of using varying authentication credentials with the relay?

**Comment by cnelissen** [comment]
@joelegasse This is just a by-product of the relay in its present form and exists with or without authentication being enabled. Currently any backend node could respond with a 4xx (busy, db error, service down, etc) and yet the relay will return a 2xx, leaving the nodes out of sync and nobody knowing that an error occurred. The only solution to the problem would be to create some sort of federation mechanism in which the relay would only respond successfully if ALL backend nodes responded successfully, otherwise you will always have the possibility that any one node failed to write at least some data.

As long as the authentication documentation includes the caveat that all backend nodes must have the same credentials to ensure proper operation, I don't see as how adding authentication is going to change the status quo. There really is no downside.

**Comment by joelegasse** [comment]
#21 has been merged.

I'm going to close this ticket as the original issue was that writes were not being forwarded with their Authentication header in-tact.

I also created #28 to continue the discussion around per-backend authentication.

**Comment by cristhianbicca** [comment]
@joelegasse  @cnelissen @rubycut @gunnaraasen @weshmashian
Hello,
In my conf I'm putting well:

[[http]]
name = "example-http"
bind-addr = ":9096"
auth-enabled = true
output = [
    { name="local1", location = "http://172.17.0.2:8086/write", username = "paul", password = "timeseries4days" },
    { name="local2", location = "http://172.17.0.5:7076/write", username = "paul", password = "timeseries4days" },
]

So when I run the relay get the following error:

 $GOPATH/bin/influxdb-relay -config relay.toml
Problem loading config file: toml: unmarshal: line 4: field corresponding to `auth-enabled' is not defined in `*relay.HTTPConfig'
2016/06/24 19:12:48 starting relays...

Can someone help me?

**Comment by joelegasse** [comment]
You shouldn't be setting authentication settings in the relay config. As of #21, the authentication will just be forwarded to the backend services. #28 was created to discuss possible designs/implications of per-backend credentials.

Enabling authentication on you backends, then sending the writes to the relay with the correct credentials should be what you're looking for.
