### ISSUE TITLE
RPM/DEB installers

### ISSUE THREAD

**Issue by cnelissen** [influxdata/influxdb-relay#16]
It would be nice if there were RPM/DEB installers for influxdb-relay available in the official yum/apt repos.

Many people don't have much experience with go and since the infrastructure is already in place it would be fairly easy to impelment and would greatly help speed up implementation for most people.

**Comment by joelegasse** [comment]
I'll look in to seeing what would be required. As of now, we're are not versioning the relay as it is very much not finalized, and major changes are happening with just about every merge (config options, behavior, etc.), although hopefully this will settle down over the next month.

I'll leave this issue open so that more people can +1 your initial comment.

**Comment by joelegasse** [comment]
#25 Has been merged, and packages can be build using the provided build script (and recommended docker container) with the instructions in the README.

At this time, influxdb-relay will not be included in official influxdata repositories.
