### ISSUE TITLE
Install Packages

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/influxdb-relay#36]
It would be useful to have install packages for `influxdb-relay` containing a sample config and service files. This would help enable automation.

@rossmcdonald @joelegasse

**Comment by rossmcdonald** [comment]
This has been discussed before, and, since we don't support influxdb-relay in an official capacity, we will not be creating packages for it. The scripts necessary to build packages are in the repo (along with [instructions](https://github.com/influxdata/influxdb-relay#building)) though, so users can pretty easily create their own if needed.
